id: P005618
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS19667
  title: ཡོངས་སུ་དག་པའི་ལྷ་སྐུ་ཐམས་ཅད་སྐྱེད་པའི་ས་བོན།
  author: ''
  volumes:
    98248c0939df4c94a807a837a03ccc91:
      image_group_id: I8LS19669
      title: ''
      volume_number: 1
      total_pages: 26
      base_file: v001.txt
